apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- ../../base

patches:
- path: patches/registry.yaml
  target:
    kind: Deployment
    name: krakend-deployment
images:
- name: thechief28/api-gateway-krakend
  newTag: 68486b52fb33a4f290549a065a63236cf56af600
