version: "3.8"
services:
  iptables-lab:
    build: .
    container_name: iptables-lab
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"  # Expose netcat to host
    stdin_open: true
    tty: true
