# docker-compose.yml
version: "3.9"

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      # System/SYS password (required)
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-password}
      # Optional: create an app user you can use immediately
      APP_USER: ${APP_USER:-admin}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD:-password}
      # Optional: set DB character set
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET:-AL32UTF8}
      # Optional: auto-generate a random SYS password instead (overrides ORACLE_PASSWORD when "true")
      # ORACLE_RANDOM_PASSWORD: "true"
    ports:
      - "1521:1521"   # SQL*Net
      # XE doesn’t ship Enterprise Manager; no 5500 mapping needed
    volumes:
      - oracle-xe-data:/opt/oracle/oradata   # persists data files
    healthcheck:
      test: ["CMD-SHELL", "echo 'exit' | sqlplus -L -s system/${ORACLE_PASSWORD}@localhost/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

volumes:
  oracle-xe-data:
