pipeline {
  agent any

  environment {
    ANSIBLE_DIR = "/home/jenkins/ansible"
  }

  stages {
    stage('Run Ansible in Docker') {
      steps {
        sh 'ansible-playbook ${ANSIBLE_DIR}/site.yml -i ${ANSIBLE_DIR}/inventories/inventory.ini'
      }
    }
  }
}
