services:
  jenkins-ansible:
    build:
      dockerfile: ./jenkins/Dockerfile
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # for Docker-in-Docker
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - ./ansible:/home/jenkins/ansible
      - ./docker-compose.yaml:/workspace/docker-compose.yaml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  target:
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    privileged: true
    expose:
      - "22"
    volumes:
      - ./ansible/scripts/init.sh:/init.sh
      - ./target/data:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/bash", "/init.sh"]

volumes:
  jenkins_home:
